git branch feature/payment-status-master-get-all-records
git branch feature/payment-status-master-get-specific-record
git branch feature/payment-status-master-add-new-records
git branch feature/payment-status-master-update-records
git branch feature/payment-status-translations
git branch feature/payment-status-translations-get-all-records
git branch feature/payment-status-translations-get-all-records-filtered-by-language
git branch feature/payment-status-translations-get-specific-record
git branch feature/payment-status-translations-add-new-records
git branch feature/payment-status-translations-update-records
git branch feature/order-payments
git branch feature/order-payments-get-all-records
git branch feature/order-payments-get-specific-record
git branch feature/order-payments-add-new-record
git branch feature/order-payments-update-record
git branch feature/user-credit-cards
git branch feature/user-credit-cards-get-all-records
git branch feature/user-credit-cards-get-specific-record
git branch feature/user-credit-cards-add-new-record
git branch feature/user-credit-cards-update-record
git branch feature/driver-ratings
git branch feature/driver-ratings-get-all-records
git branch feature/driver-ratings-get-specific-record
git branch feature/driver-ratings-add-new-records
git branch feature/driver-ratings-update-records
git branch feature/notifications
git branch feature/notifications-get-all-records
git branch feature/notifications-get-specific-record
git branch feature/notifications-add-new-record
git branch feature/notifications-update-record
git branch feature/system-messages
git branch feature/system-messages-get-all-records
git branch feature/system-messages-get-specific-record
git branch feature/system-messages-add-new-records
git branch feature/system-messages-update-records
git branch feature/language-country
git branch feature/language-country-get-all-records
git branch feature/language-country-get-specific-record
git branch feature/language-country-add-new-records
git branch feature/language-country-update-records
git branch feature/coupons
git branch feature/coupons-get-all-records
git branch feature/coupons-get-specific-record
git branch feature/coupons-add-new-records
git branch feature/coupons-update-records
git branch feature/platforms
git branch feature/platforms-get-all-records
git branch feature/platforms-get-specific-record
git branch feature/platforms-add-new-records
git branch feature/platforms-update-records
git branch feature/coupon-redemption-logs
git branch feature/coupon-redemption-logs-get-all-records
git branch feature/coupon-redemption-logs-get-specific-record
git branch feature/coupon-redemption-logs-add-new-records
git branch feature/coupon-redemption-logs-update-records
git branch feature/service-master-management
git branch feature/service-master-management-get-all-records
git branch feature/service-master-management-get-specific-record
git branch feature/service-master-management-add-new-records
git branch feature/service-master-management-update-record
git branch feature/service-translations
git branch feature/service-translations-get-all-records
git branch feature/service-translations-get-all-records-filtered-by-language
git branch feature/service-translations-get-specific-record
git branch feature/service-translations-add-new-records
git branch feature/service-translations-update-records
git branch feature/service-pricing
git branch feature/service-pricing-get-all-records
git branch feature/service-pricing-get-specific-record
git branch feature/service-pricing-add-new-records
git branch feature/service-pricing-update-record
git branch feature/additional-service-master
git branch feature/additional-service-master-get-all-records
git branch feature/additional-service-master-get-specific-record
git branch feature/additional-service-master-add-new-record
git branch feature/additional-service-master-update-record
git branch feature/additional-services-translations
git branch feature/additional-services-translations-get-all-records
git branch feature/additional-services-translations-get-all-records-filtered-by-language
git branch feature/additional-services-translations-get-specific-record
git branch feature/additional-services-translations-add-new-records
git branch feature/additional-services-translations-update-record
git branch feature/additional-service-pricing
git branch feature/additional-service-pricing-get-all-records
git branch feature/additional-service-pricing-get-specific-record
git branch feature/additional-service-pricing-add-new-records
git branch feature/additional-service-pricing-update-record
git branch feature/users-management
git branch feature/users-management-filter-by-role
git branch feature/users-management-add-new-record
git branch feature/users-management-get-specific-record
git branch feature/users-management-update-single-record
git branch feature/users-management-update-multiple-records
git branch feature/users-roles
git branch feature/users-roles-roles-get-all-records
git branch feature/users-roles-roles-get-specific-record
git branch feature/language-management
git branch feature/language-management-get-all-records
git branch feature/language-management-get-specific-record
git branch feature/language-management-add-new-records
git branch feature/language-management-update-records
git branch feature/vehicle-types-management	
git branch feature/vehicle-types-management-get-all-records
git branch feature/vehicle-types-management-get-specific-record
git branch feature/vehicle-types-management-add-new-records
git branch feature/vehicle-types-management-update-records
git branch feature/vehicle-types-translations-management
git branch feature/vehicle-types-translations-management-get-all-records
git branch feature/vehicle-types-translations-management-get-all-record-filtered-by-language
git branch feature/vehicle-types-translations-management-get-specific-record
git branch feature/vehicle-types-translations-management-add-new-records
git branch feature/vehicle-types-translations-management-update-records
git branch feature/vehicle-brands-management
git branch feature/vehicle-brands-management-get-all-records
git branch feature/vehicle-brands-management-get-specific-record
git branch feature/vehicle-brands-management-add-new-records
git branch feature/vehicle-brands-management-update-records
git branch feature/vehicle-brands-translations-management
git branch feature/vehicle-brands-translations-management-get-all-records
git branch feature/vehicle-brands-translations-management-get-all-records-filtered-by-language
git branch feature/vehicle-brands-translations-management-get-specific-record
git branch feature/vehicle-brands-translations-management-add-new-records
git branch feature/vehicle-brands-translations-management-update-records
git branch feature/vehicle-Models-management
git branch feature/vehicle-Models-management-get-all-records
git branch feature/vehicle-Models-management-get-specific-record
git branch feature/vehicle-Models-management-select-by-brand-id
git branch feature/vehicle-Models-management-add-new-records
git branch feature/vehicle-Models-management-update-records
git branch feature/vehicle-Models-translations-management
git branch feature/vehicle-Models-translations-management-get-all-records
git branch feature/vehicle-Models-translations-management-get-all-records-filtered-by-language
git branch feature/vehicle-Models-translations-management-get-specific-record
git branch feature/vehicle-Models-translations-management-select-by-brand-id
git branch feature/vehicle-Models-translations-management-add-new-records
git branch feature/vehicle-Models-translations-management-update-records
git branch feature/vehicles-management
git branch feature/vehicles-management-get-all-records
git branch feature/vehicles-management-get-specific-record
git branch feature/vehicles-management-get-by-filter
git branch feature/vehicles-management-add-new-record
git branch feature/vehicles-management-update-records
git branch feature/locations-management
git branch feature/locations-management-get-all-records
git branch feature/locations-management-get-specific-record
git branch feature/locations-management-add-new-records
git branch feature/locations-management-update-records
git branch feature/countries-management
git branch feature/countries-management-get-all-records
git branch feature/countries-management-get-specific-record
git branch feature/countries-management-add-new-records
git branch feature/countries-management-update-records
git branch feature/user-by-countries-management
git branch feature/user-by-countries-management-get-all-records
git branch feature/user-by-countries-management-get-specific-record
git branch feature/user-by-countries-management-add-new-records
git branch feature/user-by-countries-management-update-record
git branch feature/shops-management
git branch feature/shops-management-get-all-records
git branch feature/shops-management-get-specific-record
git branch feature/shops-management-add-new-record
git branch feature/shops-management-update-record